# Generated by Django 2.1.2 on 2018-10-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='organisations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('websiteUrl', models.URLField()),
                ('emailAddress', models.CharField(max_length=300)),
                ('phoneNumber', models.CharField(max_length=150)),
                ('min_age', models.IntegerField(default=16)),
                ('max_age', models.IntegerField(default=100)),
                ('contact_name', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=1)),
                ('location', models.CharField(max_length=200)),
                ('key_words', models.CharField(max_length=200)),
            ],
        ),
    ]
